-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 02:34:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crud_mysql_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crud_mysql_dev` ;

-- -----------------------------------------------------
-- Schema crud_mysql_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_mysql_dev` DEFAULT CHARACTER SET utf8 ;
USE `crud_mysql_dev` ;

-- -----------------------------------------------------
-- Table `crud_mysql_dev`.`type_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_mysql_dev`.`type_task` (
  `id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL DEFAULT '',
  `description` VARCHAR(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crud_mysql_dev`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_mysql_dev`.`task` (
  `id` INT(7) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `type_task_id` INT(4) UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL DEFAULT '',
  `description` VARCHAR(250) NOT NULL DEFAULT '',
  `done` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_task_type_task_idx` (`type_task_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_type_task`
    FOREIGN KEY (`type_task_id`)
    REFERENCES `crud_mysql_dev`.`type_task` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1000000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
